[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nok-dns"
version = "1.0.0"
description = "Cloudflare DNS updater (DDNS-like) para IP dinâmico"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "httpx>=0.27.0",
]

[project.scripts]
nok-dns = "nok-dns.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
